### PR TITLE
log_pipe build fixed for boost v1.58+ get<>

### PR DESCRIPTION
**Pull request by luav**
Remained statement fixed for the build with boost 1.58+. The cause:
```
/opt/repos/mettle/src/mettle/posix/../log_pipe.hpp:50:68:   required from here
/usr/include/boost/variant/get.hpp:212:5: error: static assertion failed: boost::variant does not contain specified type U, call to boost::get<U>(boost::variant<T...>&) will always throw boost::bad_get exception
     BOOST_STATIC_ASSERT_MSG(
     ^
[11/14] c++ -x c++ -pthread '-std=c++1...d_line.o.d -o src/libmettle/cmd_line.o
ninja: build stopped: subcommand failed.
```
See details in the pull #25.

### CODE REVIEW

**Comment by jimporter** [comment]
Whoops, sorry for missing that. It turns out it's because Boost 1.58 is unnecessarily strict with its `get<>()`, and later versions fix it. This needs tests, so I'm going to add a Travis config for 1.58 specifically as part of the fix. Thanks for the patch!

**Comment by jimporter** [comment]
I took your fix and added a test for it so this doesn't regress in c842569cfb1177e7a0b6f93d898e043285188a77. Thanks again!

**Comment by luav** [comment]
Your are welcome.

**Comment by jimporter** [comment]
[](url)
